### PR TITLE
Type forwarding support, fix #26, fix #21

### LINKED ISSUE #21: Puzzle Support for type forwarding

### LINKED ISSUE #26: Puzzle non generic Forward support

### PR DESCRIPTION
**Pull request by mauroservienti**

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny please, review.

**Comment by micdenny** [comment]
so strange that the UWP tests are actually running a full graphic instance of the application, strange and cool at the same time :smile:

**Comment by micdenny** [comment]
great, thanks!

**Comment by micdenny** [comment]
damn, I just saw that the folder `RadicalTests` should be excluded as it seeing by git as untracked item.

@mauroservienti can you exclude it please?

**Comment by mauroservienti** [comment]
doing in another branch while adding more tests

**Comment by micdenny** [comment]
> doing in another branch while adding more tests

:+1:

**Pull request merged**
