### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mauroservienti**

### CODE REVIEW

**Comment by mauroservienti** [comment]
@micdenny it's in progress, can you please do a quick review? Do you think that since the UWP thing is not yet on Nuget we should remove the Nuget/MyGet section?

**Comment by micdenny** [comment]
> Do you think that since the UWP thing is not yet on Nuget we should remove the Nuget/MyGet section?

yes please, I think we should remove the nuget/myget part, you can specify that the package will be ready as soon as we have at least a working solution.

**Comment by mauroservienti** [comment]
done @micdenny

**Comment by micdenny** [comment]
thanks!

**Pull request merged**
