### PR TITLE
Hot fix nuget package wp Issue #14

### LINKED ISSUE #14: Nuget package:Invalid Windows Phone target
Install-Package Radical.Windows.Presentation.Universal -pre
Installing 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'.
Successfully installed 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'.
Adding 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa' to App3.WindowsPhone.
Uninstalling 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'.
Successfully uninstalled 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'.
Install failed. Rolling back...
Install-Package : Could not install package 'Radical.Windows.Presentation.Universal 0.0.0.1-Alfa'. You are trying to install this 
package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or 
content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1

### PR DESCRIPTION
**Pull request by spaccabit**
closes #14

### CODE REVIEW

**Comment by mauroservienti** [comment]
Which are the differences between wp8 and wpa8?

**Comment by spaccabit** [comment]
From test i have made:
 wp8[1]    -> Silverlight Application
 wpa8[1]  -> Universal Apps

**Comment by mauroservienti** [comment]
Got it, thanks. As soon as I'm in front of the PC I'll merge it and publish new packages to NuGet.
________________________________

**Comment by mauroservienti** [comment]
published on NuGet 0.0.0.2-Alpha

**Comment by mauroservienti** [comment]
thanks.

**Pull request merged**
